import { StyleSheet } from "react-native";

export const cameraStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#0a0a0a" },
  row:  { flex: 1, flexDirection: "row" },
  cameraContainer: { flex: 3, backgroundColor: "#000" },
  webview: { flex: 1, backgroundColor: "#000" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    backgroundColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  overlayText: { color: "#666", fontSize: 14, letterSpacing: 1 },
  errorEmoji: { fontSize: 40 },
  retryBtn: {
    marginTop: 8,
    paddingHorizontal: 28,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#00e5ff15",
    borderWidth: 1,
    borderColor: "#00e5ff",
  },
  retryText: { color: "#00e5ff", fontWeight: "700", letterSpacing: 1 },
  badge: {
    position: "absolute",
    top: 14,
    left: 14,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#00000099",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 6,
    borderWidth: 1,
    borderColor: "#ffffff15",
    zIndex: 5,
  },
  liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#ff2222" },
  badgeText: { color: "#fff", fontSize: 11, fontWeight: "600", letterSpacing: 1 },
  reloadBtn: {
    position: "absolute",
    top: 10,
    right: 14,
    backgroundColor: "#00000099",
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ffffff15",
    zIndex: 5,
  },
  reloadText: { color: "#fff", fontSize: 20, lineHeight: 24 },
});

export const sensorStyles = StyleSheet.create({
  sensorPanel: {
    flex: 1,
    backgroundColor: "#111",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    gap: 10,
    borderLeftWidth: 1,
    borderLeftColor: "#222",
  },
  companyName: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 3,
    marginBottom: 2,
  },
  sensorCard: {
    width: "100%",
    backgroundColor: "#1a1a1a",
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: "#2a2a2a",
    gap: 6,
  },
  sensorTitle: {
    color: "#aaa",
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  sensorRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  sensorItem: { alignItems: "center", gap: 2 },
  divider: { width: 1, height: 30, backgroundColor: "#2a2a2a" },
  sensorLabel: { color: "#666", fontSize: 10, fontWeight: "600" },
  sensorValue: { color: "#00e5ff", fontSize: 20, fontWeight: "800" },
  sensorErrorText: { color: "#ff4444", fontSize: 10, letterSpacing: 1, textAlign: "center" },
});