import { StyleSheet } from "react-native";

export const colors = {
  bg:           "#121212",
  surface:      "#1E1E1E",
  card:         "#1A1A1A",
  cardBorder:   "#2C2C2C",
  primary:      "#4CAF50",
  secondary:    "#81C784",
  textLight:    "#E0E0E0",
  textMuted:    "#9E9E9E",
  error:        "#EF5350",
  warning:      "#FFA726",
  live:         "#EF5350",
};

export const cameraStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  row:  { flex: 1, flexDirection: "row" },
  cameraContainer: { flex: 3, backgroundColor: "#000" },
  webview: { flex: 1, backgroundColor: "#000" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    backgroundColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  overlayText: { color: colors.textMuted, fontSize: 14, letterSpacing: 1 },
  errorEmoji: { fontSize: 40 },
  retryBtn: {
    marginTop: 8,
    paddingHorizontal: 28,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: colors.primary + "20",
    borderWidth: 1,
    borderColor: colors.primary,
  },
  retryText: { color: colors.secondary, fontWeight: "700", letterSpacing: 1 },
  badge: {
    position: "absolute",
    top: 14,
    left: 14,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#00000099",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 6,
    borderWidth: 1,
    borderColor: "#ffffff15",
    zIndex: 5,
  },
  liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.live },
  badgeText: { color: colors.textLight, fontSize: 11, fontWeight: "600", letterSpacing: 1 },
  reloadBtn: {
    position: "absolute",
    top: 10,
    right: 14,
    backgroundColor: "#00000099",
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ffffff15",
    zIndex: 5,
  },
  reloadText: { color: colors.textLight, fontSize: 20, lineHeight: 24 },
  savedBadge: {
    position: "absolute",
    bottom: 14,
    left: 14,
    backgroundColor: "#00000099",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ffffff15",
    zIndex: 5,
  },
  savedText: { color: colors.textMuted, fontSize: 10, letterSpacing: 1 },
  homeBtn: {
    position: "absolute",
    bottom: 14,
    right: 14,
    backgroundColor: "#00000099",
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#ffffff15",
    zIndex: 5,
  },
});

export const sensorStyles = StyleSheet.create({
  sensorPanel: {
    flex: 1,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    padding: 6,
    gap: 5,
    borderLeftWidth: 1,
    borderLeftColor: colors.cardBorder,
  },
  companyName: {
    color: colors.secondary,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 3,
    marginBottom: 2,
  },
  sensorCard: {
    width: "100%",
    backgroundColor: colors.card,
    borderRadius: 10,
    padding: 8,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    gap: 4,
    alignItems: "center",
  },
  sensorTitle: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
    textTransform: "uppercase",
    alignSelf: "flex-start",
  },
  sensorRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
  },
  sensorItem: { alignItems: "center", gap: 2 },
  divider: { width: 1, height: 30, backgroundColor: colors.cardBorder },
  sensorLabel: { color: colors.textMuted, fontSize: 10, fontWeight: "600" },
  sensorValue: { color: colors.secondary, fontSize: 16, fontWeight: "800" },
  sensorErrorText: { color: colors.error, fontSize: 10, letterSpacing: 1, textAlign: "center" },
});

export const welcomeStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.bg,
    alignItems: "center",
    justifyContent: "center",
    gap: 32,
    paddingHorizontal: 40,
  },
  logoContainer: { alignItems: "center", gap: 10 },
  company: {
    color: colors.textLight,
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: 6,
  },
  subtitle: { color: colors.textMuted, fontSize: 13, letterSpacing: 1 },
  line: {
    width: 60,
    height: 2,
    backgroundColor: colors.primary,
    borderRadius: 2,
  },
  infoContainer: { gap: 14, alignItems: "flex-start" },
  infoItem: { flexDirection: "row", alignItems: "center", gap: 12 },
  infoIcon: { fontSize: 20 },
  infoText: { color: colors.textMuted, fontSize: 14, letterSpacing: 0.5 },
  btn: {
    backgroundColor: colors.primary + "20",
    borderWidth: 1,
    borderColor: colors.primary,
    paddingHorizontal: 36,
    paddingVertical: 14,
    borderRadius: 12,
  },
  btnText: {
    color: colors.secondary,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 1,
  },
});